version: '3.8'
services:
  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - postgres
      - minio
      - keydb
    env_file:
      - .env
    ports:
      - "3000:3000"

  postgres:
    image: postgis/postgis:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moghtareb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio_storage
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb_cache
    restart: always
    ports:
      - "6379:6379"
    command: keydb-server
    volumes:
      - keydb_data:/data

volumes:
  postgres_data:
  minio_data:
  keydb_data:
